### ISSUE TITLE
Export from testnet4000 failed

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/commercionetwork#76]
## Summary of Bug

When I tried execute command       

`cnd export --for-zero-height --height=210000 > export_genesis_210000.json` 

I got the error       

```
panic: unmarshal to string failed after 0 bytes (buffer too small): 

goroutine 1 [running]:
github.com/tendermint/go-amino.(*Codec).MustUnmarshalBinaryBare(...)
	/root/go/pkg/mod/github.com/tendermint/go-amino@v0.15.0/amino.go:358
github.com/commercionetwork/commercionetwork/x/memberships/internal/keeper.Keeper.GetStableCreditsDenom(0xc000bfa3f0, 0x16d2ea0, 0xc000c252c0, 0x16f9ca0, 0xc00094e2a0, 0x16d2ea0, 0xc000c252b0, 0xc000bfa3f0, 0x16e3120, 0xc0000b6040, ...)
	/root/commercio-chains/commercio-testnet4000/x/memberships/internal/keeper/keeper.go:157 +0x1c5
github.com/commercionetwork/commercionetwork/x/memberships.ExportGenesis(0x16e3120, 0xc0000b6040, 0x16f6aa0, 0xc0000bc680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/commercio-chains/commercio-testnet4000/x/memberships/genesis.go:70 +0x35c
github.com/commercionetwork/commercionetwork/x/memberships.AppModule.ExportGenesis(0x0, 0x0, 0xc000bfa3f0, 0x16d2ea0, 0xc000c252c0, 0x16f9ca0, 0xc00094e2a0, 0x16d2ea0, 0xc000c252b0, 0xc000bfa3f0, ...)
	/root/commercio-chains/commercio-testnet4000/x/memberships/module.go:142 +0x95
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesis(0xc000bfb0a0, 0x16e3120, 0xc0000b6040, 0x16f6aa0, 0xc0000bc680, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190930230607-cf06d3d7df95/types/module/module.go:285 +0xfe
github.com/commercionetwork/commercionetwork/app.(*CommercioNetworkApp).ExportAppStateAndValidators(0xc000bdf000, 0x33401, 0x21fded0, 0x0, 0x0, 0x0, 0xc0009ab900, 0x1, 0x0, 0x0, ...)
	/root/commercio-chains/commercio-testnet4000/app/export.go:27 +0x122
main.exportAppStateAndTMValidators(0x16e3b60, 0xc000981ae0, 0x16f8ea0, 0xc0000108b0, 0x0, 0x0, 0x33450, 0xc000981a01, 0x21fded0, 0x0, ...)
	/root/commercio-chains/commercio-testnet4000/cmd/cnd/main.go:107 +0x1a2
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc0000fa280, 0xc000c21500, 0x0, 0x2, 0x0, 0x0)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190930230607-cf06d3d7df95/server/export.go:65 +0x53d
github.com/spf13/cobra.(*Command).execute(0xc0000fa280, 0xc000c214c0, 0x2, 0x2, 0xc0000fa280, 0xc000c214c0)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c22780, 0x13039bd, 0xc000837ea8, 0xbe62b2)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000c22780, 0x14e0278, 0x12e726a, 0x10)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.3/libs/cli/setup.go:89 +0x3c
main.main()
	/root/commercio-chains/commercio-testnet4000/cmd/cnd/main.go:80 +0x79c

```

## Version

v1.3.1

## Steps to Reproduce

1. You need to access to a working and syncronized full node of commercio-testnet4000
1. Stop `cnd` deamon
1. Execute command `cnd export --for-zero-height --height=210000 > export_genesis_210000.json` 
1. If you need start the `cnd` deamon

**Comment by gsora** [comment]
After some debugging, looks like the `store.Get()` call in `GetStableCreditsDenom()` returns an empty slice: 

```
> github.com/commercionetwork/commercionetwork/x/memberships/internal/keeper.Keeper.GetStableCreditsDenom() /home/gsora/commercio/commercionetwork/x/memberships/internal/keeper/keeper.go:167 (PC: 0x1443d99)
   162: // GetStableCreditsDenom returns the denom that must be used when referring to stable credits
   163: // that can be used to purchase a membership
   164: func (k Keeper) GetStableCreditsDenom(ctx sdk.Context) (denom string) {
   165:         store := ctx.KVStore(k.storeKey)
   166:         a := store.Get([]byte(types.StableCreditsStoreKey))
=> 167:         k.cdc.MustUnmarshalBinaryBare(a, &denom)
   168:         return denom
   169: }
   170:
   171: // SetStableCreditsDenom allows to set the denom of the coins that must be used as stable credits
   172: // when purchasing a membership.
(dlv) p a
[]uint8 len: 0, cap: 0, nil
(dlv) p string(a)
""
```

**Comment by gsora** [comment]
Maybe we're missing migrations for `membership` @RiccardoM?

**Comment by RiccardoM** [comment]
The problem was in how the value was retrieved.
