### ISSUE TITLE
Error after launch cncli query account

### ISSUE THREAD

**Issue by bragaz** [commercionetwork/commercionetwork#78]
## Summary of Bug
Yesterday i found that if we try to check an account balance from `cncli` the query ends with a panic result. (This problem doesn't show off if we do the same command from REST interface).
## Version
1.3.1-32-g1c5d1d0
commit-hash:`1c5d1d0`
## Steps to Reproduce
1. `cnd start`
2. `cnd version` should be `1.3.1-32-g1c5d1d0`
3. `cncli add keys <accountName>` create an account
4. `cncli query account <accountAddress> --chain-id=<chainId>`

## Stack trace
```
\panic: Error initializing DB: resource temporarily unavailable

goroutine 1 [running]:
github.com/tendermint/tm-db.NewDB(0x1092ecd, 0xa, 0x1091c18, 0x9, 0xc000a0c780, 0x3a, 0x0, 0x40ad6b)
	/home/leonardo/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/db.go:72 +0x274
github.com/tendermint/tendermint/lite/proxy.NewVerifier(0x7ffc903b91a1, 0x15, 0xc000a0c780, 0x3a, 0x13f5480, 0xc0008807b0, 0x13ec4c0, 0x1bc0228, 0xa, 0x3, ...)
	/home/leonardo/go/pkg/mod/github.com/tendermint/tendermint@v0.32.7/lite/proxy/verifier.go:18 +0x2dd
github.com/cosmos/cosmos-sdk/client/context.CreateVerifier(0x0, 0x1407420, 0xc0008807b0, 0x7ffc903b91a1, 0x15, 0x0, 0x0, 0x13cf8a0, 0xc000010018, 0x108cca9, ...)
	/home/leonardo/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20191013030331-92ea174ea6e6/client/context/verifier.go:47 +0x1c1
github.com/cosmos/cosmos-sdk/client/context.NewCLIContextWithFrom(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/leonardo/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20191013030331-92ea174ea6e6/client/context/context.go:93 +0x612
github.com/cosmos/cosmos-sdk/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/leonardo/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20191013030331-92ea174ea6e6/client/context/context.go:104 +0x91
github.com/cosmos/cosmos-sdk/x/auth/client/cli.GetAccountCmd.func1(0xc000ca5180, 0xc000d33100, 0x1, 0x2, 0x0, 0x0)
	/home/leonardo/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20191013030331-92ea174ea6e6/x/auth/client/cli/query.go:51 +0x43
github.com/spf13/cobra.(*Command).execute(0xc000ca5180, 0xc000d330c0, 0x2, 0x2, 0xc000ca5180, 0xc000d330c0)
	/home/leonardo/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ca4780, 0xbf3ea0, 0xc000ca4780, 0x108bc3a)
	/home/leonardo/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/leonardo/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000ca4780, 0x12895b0, 0x2, 0xc000cc3120)
	/home/leonardo/go/pkg/mod/github.com/tendermint/tendermint@v0.32.7/libs/cli/setup.go:89 +0x3c
main.main()
	/home/leonardo/go/src/commercionetwork/cmd/cncli/main.go:79 +0x5b2
```

**Comment by bragaz** [comment]
Thanks to @gsora we discovered that this is my desktop problem, not a commercio bug.
